DROP TABLE INT_LOCK;
CREATE TABLE INT_LOCK (
  LOCK_KEY char(36 char) NOT NULL,
  REGION varchar2(100 char) NOT NULL,
  CLIENT_ID char(36 char) DEFAULT NULL,
  CREATED_DATE timestamp(0) NOT NULL,
  PRIMARY KEY (LOCK_KEY,REGION)
);
commit;