INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S001M201', SYSDATE, 1, 75, 90, BRANCH_SEQ.NEXTVAL, 61, 'AHUACHAPAN', 'DIGCN');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S001M301', SYSDATE, 1, 75, 90, BRANCH_SEQ.NEXTVAL, 61, 'AHUACHAPAN', 'RPRH');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S002M101', SYSDATE, 1, 76, 111, BRANCH_SEQ.NEXTVAL, 61, 'SANTA ANA', 'RC');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S002M201', SYSDATE, 1, 76, 111, BRANCH_SEQ.NEXTVAL, 61, 'SANTA ANA', 'DIGCN');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S002M301', SYSDATE, 1, 76, 111, BRANCH_SEQ.NEXTVAL, 61, 'SANTA ANA', 'RPRH');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S003M101', SYSDATE, 1, 77, 129, BRANCH_SEQ.NEXTVAL, 61, 'SONSONATE', 'DIGCN');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S003M301', SYSDATE, 1, 77, 129, BRANCH_SEQ.NEXTVAL, 61, 'SONSONATE', 'RPRH');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S004M301', SYSDATE, 1, 78, 137, BRANCH_SEQ.NEXTVAL, 61, 'CHALATENANGO', 'RPRH');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S005M301', SYSDATE, 1, 79, 172, BRANCH_SEQ.NEXTVAL, 61, 'LA LIBERTAD', 'RPRH');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S005M201', SYSDATE, 1, 79, 172, BRANCH_SEQ.NEXTVAL, 61, 'LA LIBERTAD', 'DIGCN');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S006M101', SYSDATE, 1, 80, 199, BRANCH_SEQ.NEXTVAL, 61, 'SAN SALVADOR', 'RC');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S006M201', SYSDATE, 1, 80, 199, BRANCH_SEQ.NEXTVAL, 61, 'SAN SALVADOR', 'DIGCN');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S006C101', SYSDATE, 1, 80, 199, BRANCH_SEQ.NEXTVAL, 61, 'SAN SALVADOR', 'CAJA SAN SALVADOR');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S006T101', SYSDATE, 1, 80, 199, BRANCH_SEQ.NEXTVAL, 61, 'SAN SALVADOR', 'TESORERIA');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S007M201', SYSDATE, 1, 81, 206, BRANCH_SEQ.NEXTVAL, 61, 'CUSCATLAN', 'DIGCN');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S007M301', SYSDATE, 1, 81, 206, BRANCH_SEQ.NEXTVAL, 61, 'CUSCATLAN', 'RPRH');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S008M101', SYSDATE, 1, 82, 241, BRANCH_SEQ.NEXTVAL, 61, 'LA PAZ', 'DIGCN');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S008M301', SYSDATE, 1, 82, 241, BRANCH_SEQ.NEXTVAL, 61, 'LA PAZ', 'RPRH');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S009M201', SYSDATE, 1, 83, 245, BRANCH_SEQ.NEXTVAL, 61, 'CABAÑAS', 'DIGCN');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S009M301', SYSDATE, 1, 83, 245, BRANCH_SEQ.NEXTVAL, 61, 'CABAÑAS', 'RPRH');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S010M101', SYSDATE, 1, 84, 261, BRANCH_SEQ.NEXTVAL, 61, 'SAN VICENTE', 'DIGCN');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S010M301', SYSDATE, 1, 84, 261, BRANCH_SEQ.NEXTVAL, 61, 'SAN VICENTE', 'RPRH');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S011M201', SYSDATE, 1, 85, 287, BRANCH_SEQ.NEXTVAL, 61, 'USULUTAN', 'DIGCN');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S011M301', SYSDATE, 1, 85, 287, BRANCH_SEQ.NEXTVAL, 61, 'USULUTAN', 'RPRH');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S012M101', SYSDATE, 1, 86, 304, BRANCH_SEQ.NEXTVAL, 61, 'SAN MIGUEL', 'RC');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S012M201', SYSDATE, 1, 86, 304, BRANCH_SEQ.NEXTVAL, 61, 'SAN MIGUEL', 'DIGCN');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S012M301', SYSDATE, 1, 86, 304, BRANCH_SEQ.NEXTVAL, 61, 'SAN MIGUEL', 'RPRH');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S013M201', SYSDATE, 1, 87, 326, BRANCH_SEQ.NEXTVAL, 61, 'MORAZAN', 'DIGCN');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S013M301', SYSDATE, 1, 87, 326, BRANCH_SEQ.NEXTVAL, 61, 'MORAZAN', 'RPRH');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S014M201', SYSDATE, 1, 88, 341, BRANCH_SEQ.NEXTVAL, 61, 'LA UNION', 'DIGCN');

INSERT INTO CNRPOS_SUCURSAL (CODIGO_SUCURSAL, CREATED_AT, ID_COMPANY, ID_DEPTO_BRANCH, ID_MUNI_BRANCH, ID_SUCURSAL, ID_TIPO_ESTABLECIMIENO, NOMBRE_SUCURSAL, MISIONAL)
VALUES ('S014M301', SYSDATE, 1, 88, 341, BRANCH_SEQ.NEXTVAL, 61, 'LA UNION', 'RPRH');
